### ISSUE TITLE
Make code faster

### ISSUE THREAD

**Issue by bulli92** [pygeo/rt1#2]
Make code faster by e.g. using CYTHON for critical parts

**Comment by bulli92** [comment]
Several options for speed up

1) get_fn function:
* sympy evaluation might be slow when a lot of sine, cosine functions need to be evaluated
* a solution could be that the sine, cosine values are estimated before evalf() and results are becoming part of the expression itself

2) Loop in calc_Fint can be assigned to different CPU's for parallel evaluation of get_fn

**Comment by bulli92** [comment]
implemented parallel option
however, the overhead due to the parallelization is too high at the moment; the option is therefore switched off by default.

Any further ideas for speed up???
get_fn function is the key in the end.

**Comment by raphaelquast** [comment]
implemented simplification of fn-coefficients which gives considerable speedup for monostatic evaluations (and little speedup for bistatic calculations)

**Comment by raphaelquast** [comment]
implemented ability to use numpy-arrays as input for the RT1-class
-> results in great speedup for numerical evaluation (once the fn-coefficients have been found)

**Comment by raphaelquast** [comment]
updated _extract_coefficients() function to use sympy's collect() function for getting the 
coefficients of powers of cos(theta_s).    -> results in significant speedup for fn-coefficient generation!

**Comment by bulli92** [comment]
cool, jetzt legst Du aber los!
Ich glaube da musst Du mir dann mal ne Sympy Schulung geben :-)

Gruß, Alex

Am 08.03.2017 um 18:01 schrieb raphaelquast:

**Comment by bulli92** [comment]
@raphaelquast can this be closed?

**Comment by raphaelquast** [comment]
@bulli92 ...not yet... one last thing to implement ;-) 
I found that using [symengine ](https://github.com/symengine/symengine.py) for the symbolic expansion of large sums results in a significant speedup for the fn-coefficient generation... 
Unfortunately it does not build on my pc if i use conda with python 2.7...  (with 3.6 it runs like charm)

I currently imported it using

    try:
      from symengine import expand
    except ImportError:
      from sympy import expand
- can you try if you get it running on your pc with python 2.7 ?
- should we keep the import in this way? 
- here's the improvement: 
     - Example 3 timings with sympy:
          - monostatic coefficient evaluation: **2.8 sec**
                - numerical evaluation:  0.86 sec
          - bistatic coefficient evaluation: **1.11 min**
                - numerical evaluation: 0.08 sec

     - Example 3 timings with symengine:
          - monostatic coefficient evaluation: **1.9 sec**
                - numerical evaluation:  0.86 sec
          - bistatic coefficient evaluation: **0.15 min**
                - numerical evaluation: 0.08 sec

**Comment by bulli92** [comment]
according to [pypi](https://pypi.python.org/pypi/symengine/0.2.0), symengine is supposed to work with python 2.7, but not with python 3.6  so far.

will check if it compiles for me.

**Comment by bulli92** [comment]
import works for me:

> conda install -n dev -c conda-forge python-symengine
Fetching package metadata ...........
Solving package specifications: .


python-symengi 100% |############################################| Time: 0:00:01 440.22 kB/s
(dev) alex@alexs-MacBook-Pro:geoval$ python -c "from symengine import expand"


I suggest to leave the import statement like it is. It will work for both python 2 and 3 and only fall back to sympy in case that symengine is not installed.

What would need to be then changed is also the installation documentation and in particular also .travis.yml to install the dependency.

**Comment by isuruf** [comment]
A symengine dev here.
SymEngine should work fine with python 2.7,3.3,3.4,3.5 and 3.6 (there wasn't a release after python 3.6 was released, but it works)
Only exception is that on windows, python < 3.5 is not officially supported because for eg python 2.7 is married to Visual Studio 2008 which is too old to compile symengine. You can use mingw, but there might be unexpected errors.

One more performance improvement you can make is to replace `import sympy as sp` to `import symengine.sympy_compat as sp` which avoids `sympy->symengine->sympy` conversions. This might not work, as some functionality from sympy is not ported yet. If there are some functionality you'd like to see, open an issue.

**Comment by bulli92** [comment]
@isuruf , thanks for the comments! Very helpful. We are currently starting with symengine. We'll certainly come back with a PR if we have any wishes for additional functionality.

**Comment by raphaelquast** [comment]
OK, this explains why I was not able to get symengine running on my windows-pc for python 2.7.

I updated .travis.yml to use a virtual conda-environment (adapted from [conda.io/docs/travis.html](https://conda.io/docs/travis.html)) 
This allows running the tests with symengine. Works fine for all python-versions.

A quick test of  `import symengine.sympy_compat as sp` fails due to missing `binomial` and `collect`.

**Comment by isuruf** [comment]
For those only, you can use sympy functions.

**Comment by raphaelquast** [comment]
@isuruf 
Thanks for your inputs. 

While trying to incorporate your proposed approach I found that there also seems to be a problem combining `import symengine.sympy_compat as sp`  with sympy's `collect`.

... just to give a minimal example of what i meant concerning the `collect`-function:
```
import symengine.sympy_compat as seng
from sympy import collect
x = seng.Symbol('x')
eq1 = x + 23*x**2 +2*x * x*x*x + x**3*56
sol1 = collect(eq1, x, evaluate = False)

# this results in a key-error!
sol1[x**2]   

# this gives the correct result
from sympy import Symbol as sympySymbol
sol1[sympySymbol('x')**2]
```

alternatively if the symbols are directly defined via sympy it seems to be working
```
import symengine.sympy_compat as seng
from sympy import collect, Symbol
x = Symbol('x')
eq1 = x + 23*x**2 +2*x * x*x*x + x**3*56
sol1 = collect(eq1, x, evaluate = False)

sol1[x**2]   
```

Since the speed of our code is already satisfying (for the current development stage)
I'll stick to only importing symengines `expand` for the time being as this seems to
be working without adapting the code.  (this issue will thus be closed)

**Comment by isuruf** [comment]
Ah, that happens because `collect` returns SymPy objects. I guess symengine's not ready for all those computations for now.

**Comment by raphaelquast** [comment]
Yep.... 
We'll keep an eye on the development of symengine and leave the full
incorporation of it's features as a future improvement!
